server:
  port: 8080
  servlet:
    session:
      timeout: 21600
      cookie:
        max-age: 21600

spring:
  profiles:
    active: local
  http.multipart:
    max-file-size: 5MB
    max-request-size: 5MB
  logging:
    config: logback-spring.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: exchange.xapp
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ryanluoxu@gmail.com
    fromName: Ryan Luo Xu
    password: mawzuxnzllmhcrbr
    port: 465
    protocol: smtp
    test-connection: false
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
          enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

logging:
  config: logback-spring.xml
  level:
    io.ryanluoxu.xapp:
      feign: INFO
      mapper: INFO
      aspect: INFO
      filter.LogTraceRepository: TRACE
